// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9P1Yj8IHgK1dWteVKvPczhftw0SFRrVk',
    appId: '1:780141345219:web:265b49840b095df2afa576',
    messagingSenderId: '780141345219',
    projectId: 'dawaay-2d153',
    authDomain: 'dawaay-2d153.firebaseapp.com',
    storageBucket: 'dawaay-2d153.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHF6weGBXwKKAeCENfDwZIcccZx87VOpw',
    appId: '1:780141345219:android:155c58f564a4d713afa576',
    messagingSenderId: '780141345219',
    projectId: 'dawaay-2d153',
    storageBucket: 'dawaay-2d153.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSdiTVsyeQ5PO48IKdwE5uH8GYZp3Sfso',
    appId: '1:780141345219:ios:394f4a308eb225abafa576',
    messagingSenderId: '780141345219',
    projectId: 'dawaay-2d153',
    storageBucket: 'dawaay-2d153.appspot.com',
    iosBundleId: 'com.example.dawaay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSdiTVsyeQ5PO48IKdwE5uH8GYZp3Sfso',
    appId: '1:780141345219:ios:394f4a308eb225abafa576',
    messagingSenderId: '780141345219',
    projectId: 'dawaay-2d153',
    storageBucket: 'dawaay-2d153.appspot.com',
    iosBundleId: 'com.example.dawaay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9P1Yj8IHgK1dWteVKvPczhftw0SFRrVk',
    appId: '1:780141345219:web:65e5ae94552febe9afa576',
    messagingSenderId: '780141345219',
    projectId: 'dawaay-2d153',
    authDomain: 'dawaay-2d153.firebaseapp.com',
    storageBucket: 'dawaay-2d153.appspot.com',
  );
}
